//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IdPost { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Pol { get; set; }
        public string Adress { get; set; }
        public string Photo { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
